/**
 * Case Pack PDF Generator
 * 
 * Generates a professional PDF report from CasePackMeta using pdfkit.
 * Safe to run on server (no DOM assumptions).
 */

import PDFDocument from "pdfkit";
import type { CasePackMeta, CasePackSection } from "../types/casebrain";

// Brand colors (matching dark theme)
const COLORS = {
  primary: "#14b8a6",      // Teal
  secondary: "#a855f7",    // Purple
  background: "#0f172a",   // Dark blue
  text: "#334155",         // Slate
  textLight: "#64748b",    // Light slate
  accent: "#f8fafc",       // Almost white
  danger: "#ef4444",       // Red
  warning: "#f59e0b",      // Amber
  success: "#22c55e",      // Green
};

/**
 * Generate a PDF buffer from CasePackMeta
 */
export async function generateCasePackPdf(pack: CasePackMeta): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({
        size: "A4",
        margins: { top: 50, bottom: 50, left: 50, right: 50 },
        info: {
          Title: `Case Pack - ${pack.caseTitle}`,
          Author: "CaseBrain Hub",
          Subject: "Legal Case Intelligence Report",
          Creator: "CaseBrain Hub",
        },
      });

      const chunks: Buffer[] = [];
      doc.on("data", (chunk: Buffer) => chunks.push(chunk));
      doc.on("end", () => resolve(Buffer.concat(chunks)));
      doc.on("error", reject);

      // Cover Page
      drawCoverPage(doc, pack);

      // Table of Contents
      doc.addPage();
      drawTableOfContents(doc, pack);

      // Sections
      for (const section of pack.sections) {
        doc.addPage();
        drawSection(doc, section);
      }

      // Footer on each page
      addFooters(doc, pack);

      doc.end();
    } catch (error) {
      reject(error);
    }
  });
}

function drawCoverPage(doc: PDFKit.PDFDocument, pack: CasePackMeta): void {
  const pageWidth = doc.page.width;
  const pageHeight = doc.page.height;

  // Gradient-like header bar
  doc
    .rect(0, 0, pageWidth, 200)
    .fill(COLORS.text);

  // Title
  doc
    .fillColor(COLORS.accent)
    .fontSize(32)
    .font("Helvetica-Bold")
    .text("CASE PACK", 50, 60, { width: pageWidth - 100 });

  doc
    .fontSize(14)
    .font("Helvetica")
    .text("Legal Intelligence Report", 50, 100);

  // Case title
  doc
    .fillColor(COLORS.text)
    .fontSize(24)
    .font("Helvetica-Bold")
    .text(pack.caseTitle, 50, 250, { width: pageWidth - 100 });

  // Case details
  const detailsY = 320;
  doc.fontSize(12).font("Helvetica");

  const details = [
    { label: "Practice Area", value: pack.practiceArea.replace(/_/g, " ") },
    { label: "Status", value: pack.status },
    { label: "Generated", value: new Date(pack.generatedAt).toLocaleString("en-GB") },
    { label: "Sections", value: `${pack.sections.length} sections` },
  ];

  if (pack.clientName) {
    details.unshift({ label: "Client", value: pack.clientName });
  }
  if (pack.opponentName) {
    details.splice(1, 0, { label: "Opponent", value: pack.opponentName });
  }

  details.forEach((detail, idx) => {
    const y = detailsY + idx * 25;
    doc
      .fillColor(COLORS.textLight)
      .text(detail.label + ":", 50, y, { continued: true })
      .fillColor(COLORS.text)
      .text(" " + detail.value);
  });

  // Branding footer
  doc
    .fillColor(COLORS.primary)
    .fontSize(10)
    .text("Generated by CaseBrain Hub", 50, pageHeight - 80);
  
  doc
    .fillColor(COLORS.textLight)
    .fontSize(8)
    .text("Confidential - For Internal Use Only", 50, pageHeight - 65);
}

function drawTableOfContents(doc: PDFKit.PDFDocument, pack: CasePackMeta): void {
  doc
    .fillColor(COLORS.text)
    .fontSize(20)
    .font("Helvetica-Bold")
    .text("Table of Contents", 50, 50);

  doc.moveDown(1);

  pack.sections.forEach((section, idx) => {
    const y = 100 + idx * 30;
    
    // Section number
    doc
      .fillColor(COLORS.primary)
      .fontSize(12)
      .font("Helvetica-Bold")
      .text(`${idx + 1}.`, 50, y, { continued: true, width: 30 });

    // Section title
    doc
      .fillColor(COLORS.text)
      .font("Helvetica")
      .text(` ${section.title}`, { continued: false });

    // Description if present
    if (section.description) {
      doc
        .fillColor(COLORS.textLight)
        .fontSize(10)
        .text(`   ${section.description}`, 80, y + 15);
    }
  });
}

function drawSection(doc: PDFKit.PDFDocument, section: CasePackSection): void {
  const pageWidth = doc.page.width;

  // Section header
  doc
    .rect(0, 0, pageWidth, 60)
    .fill(COLORS.text);

  doc
    .fillColor(COLORS.accent)
    .fontSize(18)
    .font("Helvetica-Bold")
    .text(section.title.toUpperCase(), 50, 20, { width: pageWidth - 100 });

  if (section.description) {
    doc
      .fontSize(10)
      .font("Helvetica")
      .text(section.description, 50, 42);
  }

  // Content
  doc
    .fillColor(COLORS.text)
    .fontSize(11)
    .font("Helvetica")
    .text(section.content, 50, 80, {
      width: pageWidth - 100,
      align: "left",
      lineGap: 4,
    });
}

function addFooters(doc: PDFKit.PDFDocument, pack: CasePackMeta): void {
  const range = doc.bufferedPageRange();
  
  for (let i = range.start; i < range.start + range.count; i++) {
    doc.switchToPage(i);

    // Page number
    doc
      .fillColor(COLORS.textLight)
      .fontSize(9)
      .text(
        `Page ${i + 1} of ${range.count}`,
        50,
        doc.page.height - 40,
        { align: "center", width: doc.page.width - 100 }
      );

    // Case reference
    doc
      .text(
        pack.caseTitle,
        50,
        doc.page.height - 28,
        { align: "center", width: doc.page.width - 100 }
      );
  }
}

