import "server-only";

import type { TimelineEvent } from "@/types";
import type PDFDocument from "pdfkit";

export type BundleLetter = {
  title: string;
  version: number;
  author: string;
  body: string;
  updatedAt: string;
  date: string;
};

export type BundleDocument = {
  name: string;
  summary?: string;
  type?: string;
  uploadDate?: string;
};

export type KeyFacts = {
  parties: Array<{ name: string; role: string }>;
  dates: Array<{ label: string; isoDate: string }>;
  amounts: Array<{ label: string; value: number; currency: string }>;
};

export type PiMetaBundle = {
  oicTrack?: string | null;
  injurySummary?: string | null;
  whiplashTariffBand?: string | null;
  prognosisMonthsMin?: number | null;
  prognosisMonthsMax?: number | null;
  psychInjury?: boolean | null;
  treatmentRecommended?: string | null;
  medcoReference?: string | null;
  liabilityStance?: string | null;
};

export type RiskFlag = {
  type: string;
  severity: string;
  description: string;
  detectedAt: string;
  resolved: boolean;
};

export type CaseBundleInput = {
  caseTitle: string;
  caseId: string;
  generatedBy: string;
  generatedAt: Date;
  summary: string;
  timeline: TimelineEvent[];
  letters: BundleLetter[];
  documents: BundleDocument[];
  firmName?: string;
  firmAddress?: string;
  defaultSignOff?: string;
  clientName?: string;
  defendantName?: string;
  practiceArea?: string;
  keyFacts?: KeyFacts;
  piMeta?: PiMetaBundle;
  riskFlags?: RiskFlag[];
};

export async function generateCaseBundlePdf(input: CaseBundleInput) {
  const PDFDocument = (await import("pdfkit")).default;
  const doc = new PDFDocument({
    size: "A4",
    margin: 50,
    info: {
      Title: `${input.caseTitle} - CaseBrain Bundle`,
      Author: input.generatedBy,
      Subject: "Case Summary Bundle",
      Producer: "CaseBrain Hub",
    },
  });

  const chunks: Buffer[] = [];
  doc.on("data", (chunk) => chunks.push(chunk as Buffer));

  const finished = new Promise<Buffer>((resolve, reject) => {
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);
  });

  drawWatermark(doc);

  // Cover page
  if (input.firmName) {
    doc
      .fontSize(18)
      .fillColor("#312E81")
      .text(input.firmName, { align: "center" })
      .moveDown(0.5);
  }
  if (input.firmAddress) {
    doc
      .fontSize(10)
      .fillColor("#475569")
      .text(input.firmAddress, { align: "center" })
      .moveDown(1);
  } else {
    doc.moveDown(1);
  }

  doc
    .fontSize(22)
    .fillColor("#312E81")
    .text("Confidential Case Bundle", { align: "center" })
    .moveDown(1.5);

  doc
    .fontSize(16)
    .fillColor("#0F172A")
    .text(input.caseTitle, { align: "center" })
    .moveDown(1);

  doc.fontSize(10).fillColor("#475569");
  doc.text(`Case Reference: ${input.caseId}`);
  if (input.clientName) {
    doc.text(`Client: ${input.clientName}`);
  }
  if (input.defendantName) {
    doc.text(`Defendant: ${input.defendantName}`);
  }
  if (input.practiceArea) {
    doc.text(`Practice Area: ${input.practiceArea}`);
  }
  doc
    .text(`Generated: ${input.generatedAt.toLocaleDateString("en-GB")} ${input.generatedAt.toLocaleTimeString("en-GB")}`)
    .text(`Generated by: ${input.generatedBy}`)
    .moveDown(2);

  addSectionHeader(doc, "Case Overview");
  doc.fontSize(12).fillColor("#1E293B").text(input.summary, { align: "left" });
  doc.moveDown(1);

  // Add disclaimer
  doc
    .fontSize(9)
    .fillColor("#64748B")
    .text(
      "This bundle is generated from extracted evidence. All facts and dates should be verified independently. This does not constitute legal advice.",
    );
  doc.moveDown(1);

  // Key Facts
  if (input.keyFacts) {
    doc.fontSize(11).fillColor("#4338CA").text("Key Facts", { underline: true });
    doc.moveDown(0.5);
    if (input.keyFacts.parties.length) {
      doc.fontSize(10).fillColor("#1E293B").text("Parties:");
      input.keyFacts.parties.forEach((party) => {
        doc
          .fontSize(10)
          .fillColor("#475569")
          .text(`  • ${party.name} (${party.role})`, { indent: 10 });
      });
      doc.moveDown(0.5);
    }
    if (input.keyFacts.dates.length) {
      doc.fontSize(10).fillColor("#1E293B").text("Key Dates:");
      input.keyFacts.dates.forEach((date) => {
        doc
          .fontSize(10)
          .fillColor("#475569")
          .text(
            `  • ${date.label}: ${new Date(date.isoDate).toLocaleDateString("en-GB")}`,
            { indent: 10 },
          );
      });
      doc.moveDown(0.5);
    }
    if (input.keyFacts.amounts.length) {
      doc.fontSize(10).fillColor("#1E293B").text("Amounts:");
      input.keyFacts.amounts.forEach((amount) => {
        doc
          .fontSize(10)
          .fillColor("#475569")
          .text(
            `  • ${amount.label}: ${new Intl.NumberFormat("en-GB", {
              style: "currency",
              currency: amount.currency,
            }).format(amount.value)}`,
            { indent: 10 },
          );
      });
      doc.moveDown(0.5);
    }
  }

  // PI Meta if available
  if (input.piMeta) {
    doc.moveDown(0.5);
    doc.fontSize(11).fillColor("#4338CA").text("PI / Clinical Negligence Details", { underline: true });
    doc.moveDown(0.5);
    if (input.piMeta.injurySummary) {
      doc.fontSize(10).fillColor("#1E293B").text("Injury Summary:");
      doc.fontSize(10).fillColor("#475569").text(input.piMeta.injurySummary, { indent: 10 });
      doc.moveDown(0.5);
    }
    if (input.piMeta.oicTrack) {
      doc.fontSize(10).fillColor("#1E293B").text(`Track: ${input.piMeta.oicTrack}`);
    }
    if (input.piMeta.whiplashTariffBand) {
      doc.fontSize(10).fillColor("#1E293B").text(`Whiplash Tariff: ${input.piMeta.whiplashTariffBand}`);
    }
    if (input.piMeta.prognosisMonthsMin || input.piMeta.prognosisMonthsMax) {
      doc
        .fontSize(10)
        .fillColor("#1E293B")
        .text(
          `Prognosis: ${input.piMeta.prognosisMonthsMin ?? "?"}–${input.piMeta.prognosisMonthsMax ?? "?"} months`,
        );
    }
    if (input.piMeta.liabilityStance) {
      doc
        .fontSize(10)
        .fillColor("#1E293B")
        .text(`Liability: ${input.piMeta.liabilityStance.charAt(0).toUpperCase() + input.piMeta.liabilityStance.slice(1)}`);
    }
    doc.moveDown(1);
  }

  doc.moveDown(1);
  addSectionHeader(doc, "Timeline");
  input.timeline.forEach((event) => {
    doc
      .fontSize(11)
      .fillColor("#1E293B")
      .text(`${event.date} — ${event.label}`, { continued: false });
    doc
      .fontSize(10)
      .fillColor("#475569")
      .text(event.description);
    doc.moveDown(0.8);
  });

  doc.addPage();
  drawWatermark(doc);

  addSectionHeader(doc, "Risk & Compliance");
  if (input.riskFlags && input.riskFlags.length > 0) {
    input.riskFlags
      .filter((flag) => !flag.resolved)
      .forEach((flag) => {
        doc
          .fontSize(11)
          .fillColor("#1E293B")
          .text(`${flag.type.replace(/_/g, " ")} (${flag.severity.toUpperCase()})`);
        doc.fontSize(10).fillColor("#475569").text(flag.description, { indent: 10 });
        doc
          .fontSize(9)
          .fillColor("#64748B")
          .text(
            `Detected: ${new Date(flag.detectedAt).toLocaleDateString("en-GB")}`,
            { indent: 10 },
          );
        doc.moveDown(0.8);
      });
  } else {
    doc
      .fontSize(10)
      .fillColor("#475569")
      .text(
        "No specific risk alerts flagged by CaseBrain for this case at this time. This does not replace professional judgment.",
      );
  }

  doc.addPage();
  drawWatermark(doc);

  addSectionHeader(doc, "Letters");
  if (input.letters.length > 0) {
    input.letters.forEach((letter, index) => {
      doc
        .fontSize(12)
        .fillColor("#1E293B")
        .text(`${index + 1}. ${letter.title} (v${letter.version})`);
      doc
        .fontSize(10)
        .fillColor("#64748B")
        .text(
          `Date: ${new Date(letter.date).toLocaleDateString("en-GB")} | Author: ${letter.author}`,
        );
      doc.moveDown(0.5);
      doc.fontSize(11).fillColor("#0F172A").text(letter.body);
      if (input.defaultSignOff) {
        doc.moveDown(1);
        doc.fontSize(11).fillColor("#0F172A").text(input.defaultSignOff);
      }
      doc.moveDown(1.5);
    });
  } else {
    doc.fontSize(10).fillColor("#475569").text("No letters generated for this case.");
  }

  doc.addPage();
  drawWatermark(doc);

  addSectionHeader(doc, "Documents");
  if (input.documents.length > 0) {
    input.documents.forEach((document) => {
      doc.fontSize(12).fillColor("#1E293B").text(document.name);
      if (document.type) {
        doc.fontSize(9).fillColor("#64748B").text(`Type: ${document.type}`);
      }
      if (document.uploadDate) {
        doc
          .fontSize(9)
          .fillColor("#64748B")
          .text(
            `Uploaded: ${new Date(document.uploadDate).toLocaleDateString("en-GB")}`,
          );
      }
      if (document.summary) {
        doc.fontSize(10).fillColor("#475569").text(document.summary);
      }
      doc.moveDown(0.8);
    });
  } else {
    doc.fontSize(10).fillColor("#475569").text("No documents attached to this case.");
  }

  doc.end();

  return finished;
}

function addSectionHeader(doc: InstanceType<typeof PDFDocument>, text: string) {
  doc
    .fontSize(14)
    .fillColor("#4338CA")
    .text(text, { underline: true })
    .moveDown(0.8);
}

function drawWatermark(doc: InstanceType<typeof PDFDocument>) {
  doc.save();
  doc
    .fontSize(60)
    .fillColor("#E0E7FF")
    .opacity(0.25)
    .rotate(-45, { origin: [300, 300] })
    .text("CaseBrain — Confidential", 0, 200, {
      align: "center",
      width: 600,
    });
  doc.restore();
}

