import type { CriminalBriefPlanProfile, CriminalBriefPlaybook } from "./types";

export const CRIMINAL_BRIEF_PLAYBOOKS: Record<CriminalBriefPlanProfile, CriminalBriefPlaybook> = {
  digital_attribution: {
    id: "digital_attribution",
    commonIssues: ["attribution", "metadata", "continuity", "source download"],
    missingMaterial: ["full phone extraction", "metadata/source download", "device continuity"],
    safeWording: {
      today: "Attribution remains provisional pending served device/source material and instructions.",
      summary: "The case turns on attribution and the limits of the served digital material.",
      chase: "The defence asks the court to record that the full extraction/source material remains outstanding.",
    },
    risks: ["Screenshots or summaries may not prove sender attribution without source material."],
    opportunities: ["Challenge attribution, continuity, and completeness of digital material."],
    doNotOverstate: ["Do not say metadata proves attribution unless full extraction is served."],
    chaseTemplates: ["Full extraction/source download and metadata continuity."],
    clientSafeStyle: "Plainly explain that messages are not the same as proved attribution.",
  },
  bwv_police_contact: {
    id: "bwv_police_contact",
    commonIssues: ["sequence", "force", "first contact", "officer account"],
    missingMaterial: ["full BWV", "BWV continuity", "officer notes"],
    safeWording: {
      today: "Sequence and force remain provisional pending served BWV and officer source material.",
      summary: "The case turns on sequence, force, and what the served BWV/officer material can actually show.",
      chase: "The defence asks the court to record that full BWV and continuity material should be served.",
    },
    risks: ["Partial or referred-only BWV cannot safely be treated as showing the incident."],
    opportunities: ["Use BWV gaps to keep sequence and force live."],
    doNotOverstate: ["Do not say BWV shows or confirms events unless the clip is served."],
    chaseTemplates: ["Full BWV clip, audit trail, and continuity/provenance."],
    clientSafeStyle: "Explain that the video position is conditional until the full clip is reviewed.",
  },
  custody_pace: {
    id: "custody_pace",
    commonIssues: ["PACE safeguards", "custody timing", "interview fairness"],
    missingMaterial: ["full custody record", "PACE interview recording", "custody risk assessments"],
    safeWording: {
      today: "Custody/PACE safeguards cannot be finally assessed until the full custody and interview material is served.",
      summary: "The case requires caution on custody safeguards and interview fairness until source records are reviewed.",
      chase: "The defence asks the court to record that full custody and interview records remain outstanding.",
    },
    risks: ["Extract-only custody records may hide timing or safeguard issues."],
    opportunities: ["Preserve PACE/safeguard points until the full record is served."],
    doNotOverstate: ["Do not say safeguards were followed from an extract-only custody record."],
    chaseTemplates: ["Full custody record, detention log, risk assessment, and interview recording."],
    clientSafeStyle: "Explain that custody fairness is being checked, not assumed.",
  },
  domestic_harassment: {
    id: "domestic_harassment",
    commonIssues: ["relationship context", "message attribution", "course of conduct", "bail/contact"],
    missingMaterial: ["message exports", "full complainant statement", "call logs"],
    safeWording: {
      today: "The defence position remains provisional pending served message/account material and instructions.",
      summary: "The case turns on relationship context, attribution, and whether the papers prove the alleged course of conduct.",
      chase: "The defence asks the court to record outstanding message/account source material and complainant statement gaps.",
    },
    risks: ["Screenshots may be incomplete or lack attribution/source context."],
    opportunities: ["Test attribution, context, and completeness of the alleged course of conduct."],
    doNotOverstate: ["Do not state the defendant sent messages unless attribution is served and safe."],
    chaseTemplates: ["Full message export, source device material, call logs, complainant MG11."],
    clientSafeStyle: "Explain contact/bail risks clearly and without final findings.",
  },
  drugs_pwits: {
    id: "drugs_pwits",
    commonIssues: ["possession", "knowledge", "intent", "continuity", "phone attribution"],
    missingMaterial: ["drug continuity", "lab report", "phone download", "search record"],
    safeWording: {
      today: "Possession, knowledge, intent and continuity remain provisional pending served drug/source material.",
      summary: "The case turns on possession, intent, continuity and any phone/search attribution evidence.",
      chase: "The defence asks the court to record outstanding continuity, lab and search/phone material.",
    },
    risks: ["Served phone/search material may strengthen possession or intent once reviewed."],
    opportunities: ["Challenge continuity, knowledge, intent and attribution gaps."],
    doNotOverstate: ["Do not rely on drug continuity unless lab/continuity material is served."],
    chaseTemplates: ["Lab report, continuity logs, search record, phone attribution material."],
    clientSafeStyle: "Explain that intent is not assumed from charge wording alone.",
  },
  violence_assault: {
    id: "violence_assault",
    commonIssues: ["sequence", "self-defence", "injury", "causation", "CCTV/BWV"],
    missingMaterial: ["medical report", "CCTV/BWV", "MG11 statements", "999/CAD"],
    safeWording: {
      today: "Sequence, injury and causation remain provisional pending served witness, medical and video/source material.",
      summary: "The case turns on sequence, causation, injury evidence and whether self-defence/first contact remains live.",
      chase: "The defence asks the court to record outstanding medical, video and sequence material.",
    },
    risks: ["Medical or video material may support the Crown account once served."],
    opportunities: ["Keep sequence, injury causation and first contact live until source material is served."],
    doNotOverstate: ["Do not state injury is consistent with assault unless medical evidence is served."],
    chaseTemplates: ["Medical report, MG11s, CCTV/BWV, CAD/999, officer notes."],
    clientSafeStyle: "Explain that sequence and injury are being checked against source material.",
  },
  sexual_abe: {
    id: "sexual_abe",
    commonIssues: ["consent", "ABE", "disclosure sensitivity", "special measures"],
    missingMaterial: ["ABE recording/transcript", "unused disclosure", "medical/forensic material"],
    safeWording: {
      today: "The defence position remains provisional pending served ABE/source material and disclosure review.",
      summary: "The case requires careful source review of ABE, consent issues and disclosure sensitivity.",
      chase: "The defence asks the court to record outstanding ABE/source and disclosure material.",
    },
    risks: ["Sensitive disclosure and ABE material can change safe advice once served."],
    opportunities: ["Preserve source-review and disclosure issues without overstating facts."],
    doNotOverstate: ["Do not summarise ABE as fact unless the served record is reviewed."],
    chaseTemplates: ["ABE recording/transcript, disclosure schedule, medical/forensic material."],
    clientSafeStyle: "Use careful, neutral language and avoid final conclusions.",
  },
  driving_motoring: {
    id: "driving_motoring",
    commonIssues: ["driver identity", "procedure", "device/calibration", "timing"],
    missingMaterial: ["device records", "calibration", "bodycam/CCTV", "procedure logs"],
    safeWording: {
      today: "Driver identity, procedure and device evidence remain provisional pending served source records.",
      summary: "The case turns on identity, procedure, timing and reliability of device/source records.",
      chase: "The defence asks the court to record outstanding device, calibration and procedure records.",
    },
    risks: ["Served procedure/device records may narrow the defence route."],
    opportunities: ["Test identity, procedure, timing and calibration/source reliability."],
    doNotOverstate: ["Do not challenge device reliability as fact without source records."],
    chaseTemplates: ["Calibration certificate, device printout, procedure log, CCTV/bodycam."],
    clientSafeStyle: "Explain procedural checks in simple terms.",
  },
  fraud_account: {
    id: "fraud_account",
    commonIssues: ["account control", "dishonesty", "loss", "bank/device source"],
    missingMaterial: ["bank records", "device/source logs", "loss schedule", "account holder evidence"],
    safeWording: {
      today: "Account control, dishonesty and loss remain provisional pending served bank/device source material.",
      summary: "The case turns on account control, attribution, dishonesty and reconciliation of loss.",
      chase: "The defence asks the court to record outstanding bank/device source and loss material.",
    },
    risks: ["Bank/device material may support account control once served."],
    opportunities: ["Challenge account control, attribution and loss reconciliation."],
    doNotOverstate: ["Do not state account control is disproved without bank/device source material."],
    chaseTemplates: ["Bank records, device logs, IP/source material, loss schedule."],
    clientSafeStyle: "Explain that account use and dishonest control are separate questions.",
  },
  robbery_id: {
    id: "robbery_id",
    commonIssues: ["identification", "participation", "CCTV", "complainant account"],
    missingMaterial: ["CCTV master", "ID procedure", "complainant MG11", "CAD/999"],
    safeWording: {
      today: "Identification and participation remain provisional pending served CCTV, ID and witness source material.",
      summary: "The case turns on identification, participation and reliability of served CCTV/witness material.",
      chase: "The defence asks the court to record outstanding CCTV, ID procedure and witness source material.",
    },
    risks: ["Served CCTV/ID material may support participation once reviewed."],
    opportunities: ["Test identification, participation and timing gaps."],
    doNotOverstate: ["Do not say CCTV excludes identification unless full footage is served."],
    chaseTemplates: ["CCTV master/full window, ID procedure material, complainant MG11, CAD/999."],
    clientSafeStyle: "Explain that identity and participation remain live pending source material.",
  },
  mixed_unclear: {
    id: "mixed_unclear",
    commonIssues: ["source truth", "missing material", "safe provisional position"],
    missingMaterial: ["MG5", "MG6", "source evidence behind allegation"],
    safeWording: {
      today: "The defence cannot safely fix a final position until the served source material is clarified.",
      summary: "The matter remains source-led and provisional because the case profile or evidence state is unclear.",
      chase: "The defence asks the court to record that source material must be clarified and timetabled.",
    },
    risks: ["Thin or mixed papers can make a confident theory unsafe."],
    opportunities: ["Use missing/source-status gaps to keep the defence position reserved."],
    doNotOverstate: ["Do not import profile-specific evidence unless the bundle supports it."],
    chaseTemplates: ["MG5/MG6 clarification and source material behind the allegation."],
    clientSafeStyle: "Explain uncertainty plainly and focus on next steps.",
  },
};
